name: 'bgg-scrape-ratings-action'
description: 'GitHub Action to scrape user ratings from BoardGameGeek.com'
author: 'David Horm'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
